CREATE TABLE course (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR,
   category VARCHAR,
   CONSTRAINT pk_course PRIMARY KEY (id)
);

INSERT
INTO
  Course
  (name, category)
VALUES
  ('Kotlin', 'Programação'),
  ('Photoshop', 'Design'),
  ('HTML', 'FrontEnd');