CREATE TABLE user_role(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      user_id BIGINT NOT NULL,
      role_id BIGINT NOT NULL,
      CONSTRAINT pk_user_role PRIMARY KEY (id)
);

ALTER TABLE user_role ADD CONSTRAINT FK_USER_ROLE_ON_USER FOREIGN KEY (user_id) REFERENCES users
(id);
ALTER TABLE user_role ADD CONSTRAINT FK_USER_ROLE_ON_ROLE FOREIGN KEY (role_id) REFERENCES role
(id);

INSERT INTO "role"
(id, "name")
VALUES(1, 'READ-WRITE');


INSERT INTO user_role
(id, user_id, role_id)
VALUES(1, 1, 1);
